apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application-sets
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ./application-sets/my-application-sets/
    repoURL: 'https://github.com/fefifofums/gitops-cert-level-2-examples'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
